version: "3.6"

services:
  meow:
    env_file:
      - ./.env
    build: "./docker"
    command: "meow-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NATS_ADDRESS: ${NATS_ADDRESS}
  query:
    env_file:
      - ./.env
    build: "./docker"
    command: "query-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NATS_ADDRESS: ${NATS_ADDRESS}
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  pusher:
    build: "./docker"
    command: "pusher-service"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
  postgres:
    build: "./docker/postgres"
    restart: "always"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
  nginx:
    build: "./docker/nginx"
    ports:
      - "8080:80"
    depends_on:
      - "meow"
      - "query"
      - "pusher"


  meow-dev:
    env_file:
      - ./.env
    build: "./docker/dev/"
    working_dir: /go/src/meow-service
    command: gin run main.go
    # command: "meow-service"
    depends_on:
      - "postgres-dev"
      - "nats-dev"
    ports:
      - "8080"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NATS_ADDRESS: ${NATS_ADDRESS}
    volumes:
      - ./:/go/src/
  query-dev:
    env_file:
      - ./.env
    build: "./docker/dev/"
    working_dir: /go/src/query-service
    command: gin run main.go
    # command: "query-service"
    depends_on:
      - "postgres-dev"
      - "nats-dev"
    ports:
      - "8080"
      - "8091:8080"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NATS_ADDRESS: ${NATS_ADDRESS}
      ELASTICSEARCH_ADDRESS: "elasticsearch-dev:9200"
    volumes:
      - ./:/go/src/
  pusher-dev:
    env_file:
      - ./.env
    build: "./docker/dev"
    working_dir: /go/src/pusher-service
    command: gin run main.go
    # command: "pusher-service"
    depends_on:
      - "nats-dev"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
    volumes:
      - ./:/go/src/
  postgres-dev:
    build: "./docker/postgres"
    restart: "always"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nats-dev:
    image: "nats-streaming:0.9.2"
    restart: "always"
  elasticsearch-dev:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
    container_name: elasticsearch-dev
  nginx-dev:
    build: "./docker/dev/nginx"
    ports:
      - "8089:80"
    depends_on:
      - elasticsearch-dev
      - "meow-dev"
      - "query-dev"
      - "pusher-dev"
